### ISSUE TITLE
Incompatibility in colors between JetBrains and  VSCode

### ISSUE THREAD

**Issue by danielpaz6** [ADMARIl/halcyon-jetbrains#23] opened 2022-12-13 22:10 UTC
Hi,

I notice a difference in the color sheet between PyCharm and VSCode.

The differences I could notice are `function` and `const` (same for `let` and `var` I assume) which are orange in JetBrains but purple in VScode.

VSCode:
![image](https://user-images.githubusercontent.com/42693974/207453624-1129a023-f6af-4819-b005-360c9e713c03.png)

Jetbrains:
![image](https://user-images.githubusercontent.com/42693974/207454552-b39d75be-9627-4a20-b4d3-567b04e6789e.png)

**Comment by ADMARIl** [comment] 2023-01-29 04:11
I noticed the same thing when I was originally developing the theme. Unfrountunatley, it seems that due to the way JetBrains handles syntax highlighting there's no way to completely replicate the way it works on vscode. However, if you have any ideas on how to solve this, I'd be open to implementing them. In the meantime, I'll close this issue as the theme is functioning as designed.

**Comment by ADMARIl** [comment] 2023-01-29 04:12
I noticed the same thing when I was originally developing the theme. Unfrountunatley, it seems that due to the way JetBrains handles syntax highlighting there's no way to completely replicate the way it works on vscode. However, if you have any ideas on how to solve this, I'd be open to implementing them. In the meantime, I'll close this issue as the theme is functioning as designed.

**Comment by ADMARIl** [comment] 2023-01-29 04:12
I noticed the same thing when I was originally developing the theme. Unfrountunatley, it seems that due to the way JetBrains handles syntax highlighting there's no way to completely replicate the way it works on vscode. However, if you have any ideas on how to solve this, I'd be open to implementing them. In the meantime, I'll close this issue as the theme is functioning as designed.

**Closed as not planned by ADMARIl** 2023-01-29 04:12 UTC
